{% set version = "9.6.5" %}
{% set libpqver = "5.9" %}

package:
  name: libpq
  version: {{ version }}

build:
  number: 0
  features:
    - vc{{ vc }}     # [win]
  always_include_files:
    - lib/libpq.so.{{ libpqver }}        # [linux]
    - lib/libpq.so.5                     # [linux]
    - lib/libpq.so                       # [linux]
    - lib/libpq.{{ libpqver }}.dylib     # [osx]
    - lib/libpq.5.dylib                  # [osx]
    - lib/libpq.dylib                    # [osx]
    - bin/pg_config                      # [unix]
    - Library/bin/libpq.dll              # [win]
    - Library/bin/pg_config.exe          # [win]
  ignore_run_exports:
    - libpq

requirements:
  host:
    # to activate the appropriate feature
    - vc {{ vc }}     # [win]
    - postgresql  {{ version }}
    - openssl
    - krb5     # [not osx]
  run:
    # to activate the appropriate feature
    - vc {{ vc }}     # [win]


test:
  commands:
    - pg_config
    - test -f $PREFIX/lib/libpq.so.{{ libpqver }}      # [linux]
    - test -f $PREFIX/lib/libpq.so.5                   # [linux]
    - test -f $PREFIX/lib/libpq.so                     # [linux]
    - test -f $PREFIX/lib/libpq.{{ libpqver }}.dylib   # [osx]
    - test -f $PREFIX/lib/libpq.5.dylib                # [osx]
    - test -f $PREFIX/lib/libpq.dylib                  # [osx]
    - IF NOT EXIST %LIBRARY_BIN%\libpq.dll EXIT 1      # [win]
    - IF NOT EXIST %LIBRARY_BIN%\pg_config.exe EXIT 1  # [win]

about:
  home: http://www.postgresql.org/
  license: PostgreSQL
  summary: The postgres runtime libraries and utilities (not the server itself)

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - mariusvniekerk
