travis:
  secure:
    BINSTAR_TOKEN: VQuaua5uk2vbJ2xhciAPQUYjFzKRoADfxCAteiK1wmVf2ij4bOyFiY5yohNJHI5Ha5LNPMRMGYj68xuGlDEIasBSDDVeAhmpI9h0JV3FytUJkm1fqP7h8LZmV2lr/H6lnRPYSRHnXSfC7l6kDUc1O9G2KQAXw3wnCGtZPXYxlf3x5UYWZqEuCyraidZNirSnTecasrDBuVJSvbAj+0YuwOUfNozsWIDP7kTWdR3/o6cqu6XsQWTu20Nnc3eLlkImEglhyn5zLbzErHinqfgWN/u/gYgyZMiLxlfn+3puKQF3b37XkZcLbW5ihiU6AGiYqZ9DsdGe6pOxr2fRs8esq2JXJxERA3N9YjzJkYntIhknwg7AX/VU6WCxlmKoU3CtAnO8z2q2TsoZcKnmzciYdq5vuEKM39r11vcQOoW1K2ZdzAC/QsYfun0/XAfsqLSVg16Y6N+C3ggGEa1yxC4AifT4cPXwkkgwldDR/0Jy4VPMSMYuLH6UAl9gIYsnHvcLgaGDSpahw5tCeqch0kr5bixiXd3TXYjsKGo6JvnwUbnn6qUGcdaDMpgsRSwOaTvf96lOcrxboKuPbnQvDSjhTaiINeM03WByKgik7TmRqrf2hS+zfKzLatPr45mqlviAbyLYV6QZc4nzrFnnWRzKbio/31KORE5maw/mcAG6h74=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
